### ISSUE TITLE
Allow the height of the shadow to be changed

### ISSUE THREAD

**Issue by blasten** [PolymerElements/paper-header-panel#79]
Users may want to customize the height of the shadow, so some of these properties can be moved before the `@apply`.

``` css
  #dropShadow {
        @apply(--paper-header-panel-shadow);
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        height: 6px;
        pointer-events: none;
        -webkit-transition: opacity 0.5s;
        transition: opacity 0.5s;
        opacity: 0;
      }
```
